import Layout from '../components/layout';
import Head from "next/head";
import Curri from '../components/content/curri';
import Curria from '../components/content/curria';

export default function Recruiting() {
  return (
    <Layout>
      <Head>
        <title>DAYS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="flex min-h-screen flex-col items-center justify-center text-gray-600 body-font">
       <div className="container mx-auto flex px-5 py-24 items-center justify-center flex-col">
         <Curri/>
       </div>
       <div className="container mx-auto flex px-5 py-24 mb-48 items-center justify-center flex-col">
         <Curria/>
       </div>
      </section>
    </Layout>
  )
}