import Layout from '../components/layout';
import Head from "next/head";

export default function Dvf() {
    return (
        <Layout>
          <div className="flex flex-col items-center justify-center min-h-screen px-3 mb-10">
                <Head>
                     <title>DAYS</title>
                     <meta name="description" content="Generated by create next app" />
                     <link rel="icon" href="/favicon.ico" />
                </Head>
            <h1 className="text-4xl font-bold sm:text-6xl">
              총 프로젝트
            </h1>


          </div>

        </Layout>

    );
}