import Layout from '../components/layout';
import Head from "next/head";
import{TOKEN,DATABASE_ID} from "../config";
import ProjectItem from '../components/projects/project-item';

export default function Projects({projects}) {

    console.log(projects);

    return(
        <Layout>
          <div className="flex flex-col items-center justify-center min-h-screen px-3 mb-10 mt-20">
                <Head>
                     <title>DAYS</title>
                     <meta name="description" content="Generated by create next app" />
                     <link rel="icon" href="/favicon.ico" />
                </Head>
            <h1 className="text-5xl font-bold sm:text-5xl">
              D.V.F 프로젝트: 
              <span className="pl-4 text-blue-500">{projects.results.length}</span>
            </h1>

            <div className="grid grid-cols-1 gap-8 p-12 m-4 md:grid-cols-2">
            {projects.results.map((aProject)=>(
              <ProjectItem key={aProject.id}data={aProject}/>
            ))}
            </div>

          </div>

        </Layout>
    );
}

export async function getStaticProps() {

    const options = {
        method: 'POST',
        headers: {
          accept: 'application/json',
          'Notion-Version': '2022-06-28',
          'content-type': 'application/json',
          authorization: `Bearer ${TOKEN}`
        },
        bbody: JSON.stringify({
          sorts: [
              {
                  "property": "Tag",
                  "direction": "ascending"
              }
          ],
          page_size: 100
       })
      };
      
      const res = await fetch(`https://api.notion.com/v1/databases/${DATABASE_ID}/query`, options)

      const projects = await res.json()
      
    

      const projectNames= projects.results.map((aProject)=>(
        aProject.properties.Name.title[0] ? aProject.properties.Name.title[0].plain_text: ''
      ))

      console.log(`projectNames: ${projectNames}`);


    
    return {
      props: {projects}, // will be passed to the page component as props
    }
  }